server:
  port: 8080
spring:
  application:
    name: energy-optimizer
  devtools:
    restart:
      additional-exclude: log/**
  jmx:
    default-domain: "${spring.application.name}"
  web:
    locale: en_EN
    locale-resolver: fixed
  datasource:
    url: ${DB_CONNECT:jdbc:h2:mem:db;DB_CLOSE_DELAY=-1}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:sa}
management:
  endpoints:
    web:
      exposure:
        include: "health"
logging:
  file:
    path: "log/"
    name: "${logging.file.path}${spring.application.name}.log"
    max-history: 30
    max-size: 50MB
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS,Europe/Berlin} [%thread] %-5level %logger{36} : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS,Europe/Berlin} [%thread] %-5level %logger{36} : %msg%n"
app:
  login:
    user-name: ${LOGIN_USER:admin}
    password: ${LOGIN_PASS:pass}
  pvPlants:
    - latitude: ${PV_PLANT_LATITUDE1:54.9}
      longitude: ${PV_PLANT_LONGITUDE1:25.3}
      declination: ${PV_PLANT_DECLINATION1:37}
      azimuth: ${PV_PLANT_AZIMUTH1:0}
      kwPeak: ${PV_PLANT_KWPEAK1:1}
    - latitude: ${PV_PLANT_LATITUDE2:54.9}
      longitude: ${PV_PLANT_LONGITUDE2:25.3}
      declination: ${PV_PLANT_DECLINATION2:37}
      azimuth: ${PV_PLANT_AZIMUTH2:0}
      kwPeak: ${PV_PLANT_KWPEAK2:1}
    - latitude: ${PV_PLANT_LATITUDE3:54.9}
      longitude: ${PV_PLANT_LONGITUDE3:25.3}
      declination: ${PV_PLANT_DECLINATION3:37}
      azimuth: ${PV_PLANT_AZIMUTH3:0}
      kwPeak: ${PV_PLANT_KWPEAK3:1}
