server:
  port: 8080
spring:
  application:
    name: energy-optimizer
  devtools:
    restart:
      additional-exclude: log/**
  jmx:
    default-domain: "${spring.application.name}"
  web:
    locale: en_EN
    locale-resolver: fixed
  datasource:
    url: ${DB_CONNECT:jdbc:h2:mem:db;DB_CLOSE_DELAY=-1}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:sa}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
management:
  endpoints:
    web:
      exposure:
        include: "health"
logging:
  file:
    path: "log/"
    name: "${logging.file.path}${spring.application.name}.log"
    max-history: 30
    max-size: 50MB
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS,Europe/Berlin} [%thread] %-5level %logger{36} : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS,Europe/Berlin} [%thread] %-5level %logger{36} : %msg%n"
app:
  scheduled:
    enabled: ${ENABLE_SCHEDULER:false}
  login:
    user-name: ${LOGIN_USER:admin}
    password: ${LOGIN_PASS:pass}
  pvPlants:
    - latitude: ${PV_PLANT_LATITUDE1:1}
      longitude: ${PV_PLANT_LONGITUDE1:1}
      declination: ${PV_PLANT_DECLINATION1:1}
      azimuth: ${PV_PLANT_AZIMUTH1:1}
      kwPeak: ${PV_PLANT_KWPEAK1:1}
    - latitude: ${PV_PLANT_LATITUDE2:2}
      longitude: ${PV_PLANT_LONGITUDE2:2}
      declination: ${PV_PLANT_DECLINATION2:2}
      azimuth: ${PV_PLANT_AZIMUTH2:2}
      kwPeak: ${PV_PLANT_KWPEAK2:2}
    - latitude: ${PV_PLANT_LATITUDE3:3}
      longitude: ${PV_PLANT_LONGITUDE3:3}
      declination: ${PV_PLANT_DECLINATION3:3}
      azimuth: ${PV_PLANT_AZIMUTH3:3}
      kwPeak: ${PV_PLANT_KWPEAK3:3}
